// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: levels_entities.sql

package repository

import (
	"context"
)

const newEntityLevel = `-- name: NewEntityLevel :exec
INSERT INTO "levels_entities" (level_id, entity_id, health_points, x_coord, y_coord, number) VALUES (?, ?, ?, ?, ?, ?)
`

type NewEntityLevelParams struct {
	LevelID      int64 `json:"level_id"`
	EntityID     int64 `json:"entity_id"`
	HealthPoints int64 `json:"health_points"`
	XCoord       int64 `json:"x_coord"`
	YCoord       int64 `json:"y_coord"`
	Number       int64 `json:"number"`
}

func (q *Queries) NewEntityLevel(ctx context.Context, arg NewEntityLevelParams) error {
	_, err := q.db.ExecContext(ctx, newEntityLevel,
		arg.LevelID,
		arg.EntityID,
		arg.HealthPoints,
		arg.XCoord,
		arg.YCoord,
		arg.Number,
	)
	return err
}
