// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type Entities struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Faction string `json:"faction"`
}

type Levels struct {
	ID          int64         `json:"id"`
	Name        string        `json:"name"`
	ImagePath   string        `json:"image_path"`
	GridWidth   int64         `json:"grid_width"`
	GridColor   string        `json:"grid_color"`
	GridSpacing sql.NullInt64 `json:"grid_spacing"`
}

type LevelsEntities struct {
	LevelID      int64 `json:"level_id"`
	EntityID     int64 `json:"entity_id"`
	HealthPoints int64 `json:"health_points"`
	XCoord       int64 `json:"x_coord"`
	YCoord       int64 `json:"y_coord"`
	Number       int64 `json:"number"`
}
